name: Build

on:
  push:
    branches: [ main ]
    paths-ignore: '**.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ROS_DISTRO: [humble, noetic]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          file: ${{github.workspace}}/docker/${{ matrix.ROS_DISTRO }}/Dockerfile
          context: .
          tags: ${{secrets.DOCKER_USERNAME}}/direct_visual_lidar_calibration:${{ matrix.ROS_DISTRO }}
          push: true
